apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.3.2
          args:
            - --init-file=/docker-entrypoint-initdb.d/init.sql
          envFrom:
          - secretRef:
              name: maria-db-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc  # If using PVC
        - name: init-scripts
          configMap:
            name: db-init-script  # Name of the ConfigMap

