apiVersion: v1
kind: Pod
metadata:
  name: mysql-client-pod
  namespace: test
spec:
  containers:
    - name: mysql-client
      image: mysql:5.7
      command: ["sleep", "infinity"]  # Keeps the container running
      env:
        - name: MYSQL_ROOT_PASSWORD  # Provide the MariaDB root password
          value: YbY4XkR$vrAaWKS  # Replace with your actual MariaDB root password
        - name: MYSQL_HOST  # Provide the MariaDB service name
          value: mysql-service  # Replace with your MariaDB service name
      volumeMounts:
        - name: client-scripts
          mountPath: /scripts  # Mount a directory for any SQL scripts
  volumes:
    - name: client-scripts
      emptyDir: {}  # Create an empty directory for SQL scripts

